version: "2"

services:
  ts3-api:
    build: .

  haproxy:
    image: 'dockercloud/haproxy'
    links:
     - ts3-api
    ports:
     - "9652:80"
     - "1936:1936"
    environment:
      STATS_AUTH: "change:me"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
